export interface EnvConfig {
	SEPOLIA_URL: string;
	SEPOLIA_PRIVATE_KEY: string;
	SEPOLIA_PUBLIC_KEY: string;
	PINATA_API_KEY: string;
	PINATA_API_SECRET: string;
	NFT_CONTRACT_ADDRESS: string;
	PUBLIC_KEYS: string;
	PRIVATE_KEYS: string;
	PAYMENT_CONTRACT_ADDRESS: string;
	WALLET_CONTRACT_ADDRESS: string;
	PRODUCT_CONTRACT_ADDRESS: string;
}
